# Generated by Django 5.0.3 on 2024-04-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='bluriness_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='is_blurry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='threshold',
            field=models.IntegerField(default=100),
        ),
    ]
